#include <iostream>
using namespace std;

// Function to calculate the sum of all numbers generated by the doubling machine
int doublingMachineSum(int n) {
    int currentNumber = 1; // Start from 1
    int sum = 0;

    // Loop through each press
    for (int i = 1; i <= n; ++i) {
        sum += currentNumber; // Add the current number to the sum
        currentNumber *= 2;   // Double the current number
    }

    return sum; // Return the total sum
}

int main() {
    int n;
    cout << "Enter the number of button presses (n): ";
    cin >> n; // Input the number of presses

    // Calculate and output the sum
    cout << "Sum of all numbers: " << doublingMachineSum(n) << endl;

    return 0;
}
